// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package pusher.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import pusher.proxies.constants.Constants;
import com.pusher.rest.Pusher;
import pusher.helpers.PusherFactory;

public class sendEvent extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String Channel;
	private java.lang.String Event;
	private java.lang.String Data;

	public sendEvent(IContext context, java.lang.String Channel, java.lang.String Event, java.lang.String Data)
	{
		super(context);
		this.Channel = Channel;
		this.Event = Event;
		this.Data = Data;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		Pusher pusherObject = PusherFactory.getPusher(Constants.getappId(), Constants.getapiKey(), Constants.getappSecret(), Constants.getcluster());
		pusherObject.trigger(this.Channel, this.Event, this.Data);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "sendEvent";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
